export const ruleForm = {
  ID: '',
  name: '',
  gender: '',
  status: '',
  mobile: '',
  emp_no: '',
  nation: '',
  age: '',
  politic_status: '',
  id_card: '',
  interview_comment: '',
  resume: '',
  email: '',
  personal_email: '',
  wx_work: '',
  tapd: '',
  service_line: '',
  department_id: '',
  department: {},
  level_id: '',
  level: {},
  create_time: '',
  position: '',
  plan_date: '',
  entry_date: '',
  resignation_date: '',
  reason: '',
  req_user: '',
  employee_basic: {
    ID: 16,
    employee_id: 16,
    id_card_front: '',
    id_card_back: '',
    debit_card1: '',
    issuing_bank1: '',
    issuing_bank1_detail: '',
    debit_card1_front: '',
    debit_card2: '',
    issuing_bank2: '',
    issuing_bank2_detail: '',
    debit_card2_front: '',
    field_53: '',
    public_fund: '',
    degree: '',
    degree_property: '',
    major: '',
    graduation_school: '',
    degree_certification_copy: '',
    degree_verification: '',
    en_skill: '',
    other_language_skill: '',
    birthday: '',
    birthplace: '',
    inhabited_city: '',
    inhabited_district: '',
    inhabited_address: '',
    marriage: '',
    children: '',
    relations: [
      { name: '', Relation: '父亲' },
      { name: '', Relation: '母亲' },
      { name: '', Relation: '配偶' }
    ],
    contacts: [
      { name: '', Relation: '父亲' },
      { name: '', Relation: '母亲' }
    ]
  }
}
